### ISSUE TITLE
Boonagev system, Duil planet tribute bug

### ISSUE THREAD

**Issue by OcelotWalrus** [Petersupes/sheragi-rebirth#1]
So i found a bug with the Duil planet. The Duil planet is a Shegari Dishonoured governed planet but when you ask for tributes, it is a Sheragi fleet that spawns.

EDIT:
A link for my pull request to fix the bug: https://github.com/Petersupes/sheragi-rebirth/pull/2

**Comment by Petersupes** [comment]
Problem fixed, thank you.
