### ISSUE TITLE
Sprites and a question for you

### ISSUE THREAD

**Issue by TheGiraffe3** [Petersupes/sheragi-rebirth#4]
I am making a set of aliens which I hope to someday have in vanilla, called the [Jibauni](https://github.com/TheGiraffe3/Jibauni). I am also trying to re-add the Sheragi in my work, but I'm kind of stuck on sprites I can use. (I can't make my own, because I'm not good at Blender).

Is it okay if I use the sprites you have here? If so, would you mind sharing the source files you used to make them? Thanks!

**Comment by TheGiraffe3** [comment]
@Petersupes did you see this?

**Comment by TheGiraffe3** [comment]
@Petersupes could you take a look at this please?

**Comment by Petersupes** [comment]
I'm not working on this plugin anymore, but feel free to use my sprites.

**Comment by TheGiraffe3** [comment]
The problem is that I have to have .blend files to go along with the sprites. Are there those?

**Comment by Petersupes** [comment]
https://github.com/Petersupes/Sheragi-Rebirth-Assets

**Comment by TheGiraffe3** [comment]
Thanks. It is quite kind of you.
